name: 3. Update Latest Episodes

on:
  schedule:
    - cron: '0 * * * *' # Jalankan setiap 1 jam
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      # PERBAIKAN: Menggunakan Action khusus untuk setup Chrome dan Chromedriver
      - name: Setup Chrome & Chromedriver
        uses: nanasess/setup-chromedriver@v2

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run latest scraper script
        timeout-minutes: 15 # Timeout bisa dikurangi karena proses lebih cepat
        run: python 3_update_latest.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add anime_homepage.json
          git diff --staged --quiet || (git commit -m "Update homepage data" && git push)
